# Generated by Django 2.2.2 on 2019-06-28 16:11

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightlyuser',
            name='photograph',
            field=django_cryptography.fields.encrypt(models.ImageField(
                default='img/default_user_photo.png', upload_to='img', verbose_name='Passport Photograph')),
        ),
    ]
